### PR TITLE
Fixed withParalax not triggering update after the block is moved - closes #42

### LINKED ISSUE #42: withParalax isn't triggering update after the block is moved
**Describe the bug**
WP 5.3 adds an "[animation](https://wptavern.com/gutenberg-6-1-introduces-animation-to-block-moving-actions-adds-block-based-widgets-screen-experiments)" when you click the move block up/down buttons. It's actually a css transform without a transition or a set duration ([react-spring](https://github.com/react-spring/react-spring)). When you move a block it will only update the position when the animation starts, not when it ends. This results in a black space above or below the image. `transitioned` event doesn't work because it's not a transition. `MutationObserver` works in this case...

**Screenshots**
https://imgur.com/ekzUsCJ

### PR DESCRIPTION
**Pull request by acosmin**
**Description**
WP 5.3 adds an "[animation](https://wptavern.com/gutenberg-6-1-introduces-animation-to-block-moving-actions-adds-block-based-widgets-screen-experiments)" when you click the move block up/down buttons. It's actually a css transform without a transition or a set duration ([react-spring](https://github.com/react-spring/react-spring)). When you move a block it will only update the position when the animation starts, not when it ends. This results in a black space above or below the image. `transitioned` event doesn't work because it's not a transition. `MutationObserver` works in this case...

**How has this been tested?**
WP 5.3

**Types of changes**
What types of changes does your code introduce?
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Additional context**
Whitout changes - https://imgur.com/ekzUsCJ
With changes -  https://imgur.com/FLmYdhO

### CODE REVIEW

File: src/components/with-parallax/index.js [hunk 1]
```diff
@@ -43,6 +37,28 @@ const withParallax = function( WrappedComponent ) {
 			const scrollContainer = document.getElementsByClassName( 'edit-post-layout__content' )[ 0 ];
 			window.addEventListener( 'resize', this.updateHandler );
 			scrollContainer.addEventListener( 'scroll', this.updateHandler );
+
+			this.observers = findParents( this.container, '.wp-block' ).map( block => {
+				const observer = new MutationObserver( movements => {
+					movements.forEach( movement => {
+						if ( 'style' === movement.attributeName ) {
+							if ( movement.oldValue.includes( 'transform: translate3d' ) ) {
```
Comment (razwan) [inline src/components/with-parallax/index.js]: Would we get in trouble if we get rid of this condition? I feel like there could also be other style changes that would require `updateDimensions`. Also we would also be covered if `translate3d` turns into `translateY` at some point.

File: src/components/with-parallax/index.js [hunk 2]
```diff
@@ -43,6 +37,28 @@ const withParallax = function( WrappedComponent ) {
...
+
+				observer.observe( block, {
+					attributes: true,
+					attributeOldValue: true,
+					childList: false,
+					subtree: false,
+				} );
+
+				return observer;
+			} );
```
[the remark this answers is not in the document]
Comment (acosmin) [reply src/components/with-parallax/index.js]: If you plan on using it with other components, then yes... For the current use case I don't think it's needed.

File: src/components/with-parallax/index.js (hunk 1 above)
Comment (acosmin) [reply src/components/with-parallax/index.js]: If we remove the conditions it would update on any attribute change, classes, data sets and all style changes. For example, it will trigger an update on `is-hovered`... even if nothing changes.

Comment (razwan) [reply src/components/with-parallax/index.js]: I was referring only to the latter condition comparing the old value of the style tag but since this is just an assumption I'll merge the pull request and wait to see what the future brings us. Congrats and thank you for your first contribution @acosmin

Comment (acosmin) [reply src/components/with-parallax/index.js]: Thanks 😄 you could probably remove that condition, there aren't many styles applied on that element...
