### PR TITLE
Fix Slideshow vertical and horizontal alignment controls

### LINKED ISSUE #164: [Slideshow] Overlay text shows up faded in the Gutenberg editor
The text displayed in the Gutenberg editor shows up very faded although in the live page it shows up just fine:
Screenshot 2020-05-21 at 12 37 39

I'm using Rosa2 1.2.0 and Nova Blocks 1.4.2

### LINKED ISSUE #165: [Slideshow] Overlay text Horizontal and Vertical alignment settings not working in Gutenberg editor
When using the Horizontal and Vertical settings for the overlay text (image title) in the Gutenberg editor, the text stays still and doesn't move according to what I select.

Screen Recording 2020-05-21 at 12 42 PM

When I check the live page, the settings seem to apply correctly.
 
I'm using Nova Blocks 1.4.2 and Rosa 2 1.2.0

### PR DESCRIPTION
**Pull request by razwan**
Fixes #164
Fixes #165 

**Types of changes**
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: src/blocks/slideshow/frontend.js [hunk 1]
```diff
@@ -9,7 +9,6 @@ import {
 const BLOCK_SELECTOR = '.novablocks-slideshow';
 const SLIDER_SELECTOR = '.novablocks-slideshow__slider';
 const SLIDE_SELECTOR = '.novablocks-slideshow__slide';
-const CONTENT_SELECTOR = '.novablocks-slideshow__content';
 const BACKGROUND_SELECTOR = '.novablocks-slideshow__background';
```
Comment (madalingorbanescu) [inline src/blocks/slideshow/frontend.js:12]: We can delete that, because we are not using it.
